### ISSUE TITLE
Suggestion: Stack instead of Queue option

### ISSUE THREAD

**Issue by Nullspeaker** [FocaBot/FocaBot#15]
Allow DJ+ role to change from a music queue to a music stack

**Comment by TheBITLINK** [comment]
What do you mean with "stack"?
A mode where the playlist gets played from the last item to the first one?

**Comment by Nullspeaker** [comment]
Yeah -- when a song ends, play the most recently added song.

**Comment by TheBITLINK** [comment]
I've implemented an `inversePlaylist` parameter in the `azarasi` branch.
```
f'config inversePlaylist true
```
If you're using the npm package, just update it to the latest version.

The `azarasi` branch will be merged into `master` in a few days, i'll leave this issue open until then.
