### ISSUE TITLE
Can't play a song

### ISSUE THREAD

**Issue by alarictabaries** [FocaBot/FocaBot#4]
Hello,
I can play a song with the FocaBot hosted bot but when I try with the self hosted one, the bot join the channel, send this error message : "Couldn't join to the voice channel. Skipping..." and then leave. The error happens with a YouTube link and a MP3 link.
I have FFMPEG version 3.2.5-1 ; NodeJS v7.10.1.

Error screenshot : [here](https://altab.fr/snaps/Discord_2017-08-19_22-25-21.png) (it get the length.. etc.).

**Comment by TheBITLINK** [comment]
Are you getting any output in the console when the error happens?
Also, what OS is the bot running on?

**Comment by alarictabaries** [comment]
Solved : switched from default OVH nameservers to Google nameservers in /etc/resolv.conf.
